version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app/upload:/app/upload
    env_file:
      - .env # Menunjukkan Docker Compose untuk membaca .env file
